export const WEEKDAYS = {
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
};

export const TIMETABLE = {
  [WEEKDAYS.Monday] : {
    id: 1,
    day: "Понеділок",
    lesson_1: "Укр.мова(Читання)",
    lesson_2: "Математика",
    lesson_3: "Англ.мова/Письмо(1п.)",
    lesson_4: "Письмо/Англ.мова(2п.)",
    lesson_5: "ЯДС",
  },
  [WEEKDAYS.Tuesday] : {
    id: 2,
    day: "Вівторок",
    lesson_1: "Укр.мова(Читання)",
    lesson_2: "Фiзкультура",
    lesson_3: "Укр.мова(Письмо)",
    lesson_4: "Математика",
    lesson_5: "ЯДС",
  },
  [WEEKDAYS.Wednesday] : {
    id: 3,
    day: "Середа",
    lesson_1: "ЯДС(T.)",
    lesson_2: "Укр.мова(Читання)",
    lesson_3: "Англ.мова/Письмо(2п.)",
    lesson_4: "Письмо/Англ.мова(1п.)",
    lesson_5: "",
  },
  [WEEKDAYS.Thursday] : {
    id: 4,
    day: "Четвер",
    lesson_1: "ЯДС",
    lesson_2: "Математика",
    lesson_3: "Мистецтво (образотворче)",
    lesson_4: "Хореографiя",
    lesson_5: "",
  },
  [WEEKDAYS.Friday] : {
    id: 5,
    day: "П'ятниця",
    lesson_1: "Укр.мова(Читання)",
    lesson_2: "Математика",
    lesson_3: "Мистецтво(музичне)",
    lesson_4: "Фiзкультура",
    lesson_5: "Укр.мова(Письмо)",
  },
  [WEEKDAYS.Saturday] : {
    id: 6,
    day: "Субота",
    lesson_1: "Вихідний",
    lesson_2: "",
    lesson_3: "",
    lesson_4: "",
    lesson_5: "",
  },
  [WEEKDAYS.Sunday] :  {
    id: 7,
    day: "Неділя",
    lesson_1: "Вихідний",
    lesson_2: "",
    lesson_3: "",
    lesson_4: "",
    lesson_5: "",
  },

};
