export const WEEKDAYS = {
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
};

export const TIMETABLE = {
  [WEEKDAYS.Monday] : {
    id: 1,
    day: "Понеділок",
    lesson_1: "ЯДС",
    lesson_2: "Читання",
    lesson_3: "Англ.мова",
    lesson_4: "Письмо",
    lesson_5: "Математика",
  },
  [WEEKDAYS.Tuesday] : {
    id: 2,
    day: "Вівторок",
    lesson_1: "ЯДС",
    lesson_2: "Фiзкультура",
    lesson_3: "Письмо",
    lesson_4: "Читання",
    lesson_5: "Математика",
  },
  [WEEKDAYS.Wednesday] : {
    id: 3,
    day: "Середа",
    lesson_1: "ЯДС",
    lesson_2: "Мистецтво",
    lesson_3: "Англ.мова",
    lesson_4: "Письмо",
    lesson_5: "",
  },
  [WEEKDAYS.Thursday] : {
    id: 4,
    day: "Четвер",
    lesson_1: "Читання",
    lesson_2: "Письмо",
    lesson_3: "Математика",
    lesson_4: "Хореографiя",
    lesson_5: "",
  },
  [WEEKDAYS.Friday] : {
    id: 5,
    day: "П'ятниця",
    lesson_1: "ЯДС",
    lesson_2: "Читання",
    lesson_3: "Математика",
    lesson_4: "Фiзкультура",
    lesson_5: "Мистецтво (музичне)",
  },
  [WEEKDAYS.Saturday] : {
    id: 6,
    day: "Субота",
    lesson_1: "Вихідний",
    lesson_2: "",
    lesson_3: "",
    lesson_4: "",
    lesson_5: "",
  },
  [WEEKDAYS.Sunday] :  {
    id: 7,
    day: "Неділя",
    lesson_1: "Вихідний",
    lesson_2: "",
    lesson_3: "",
    lesson_4: "",
    lesson_5: "",
  },

};
